### ISSUE TITLE
execute_cql3_query methode is mising from perlcassa.pm

### ISSUE THREAD

**Issue by geetanjaligandhi** [mkjellman/perlcassa#29]
Hi

execute_cql3_query methode is mising from perlcassa.pm. Please share its implemetation. Just browsing i fount its 0.5 version which include above method in perlcassa.pm

But now running the testcases is throwing
TApplicationException=HASH(0x9aa82c0)# Looks like your test exited with 255 just after 1. error

Running 

$res = $obj->exec("CREATE KEYSPACE $test_keyspace WITH REPLICATION = {'CLASS' : 'SimpleStrategy', 'replication_factor': 1};");
ok($res, "Create test keyspace ($test_keyspace).");
Throwing TApplicationException=HASH(0x9aa82c0)# Looks like your test exited with 255 just after 1. error 

Please help me with the solution

Thanks
Geetanjali

**Comment by mkjellman** [comment]
execute_cql3_query is from the Cassandra module generated by Thrift. Sounds like that module didn't make it into your Perl path..

**Comment by Lanzaa** [comment]
I'm not sure how execute_cql3_query was missing. That is very odd. If possible could you tell us how to reproduce that issue?

As for the test cases failing, it is a stupid little problem. The 'CLASS" needs to be lowercase 'class'. so instead of:

``` perl
$res = $dbh->exec("CREATE KEYSPACE $test_keyspace WITH REPLICATION = { 'CLASS': 'SimpleStrategy', 'replication_factor': 1};");
```

it needs to be

``` perl
$res = $dbh->exec("CREATE KEYSPACE $test_keyspace WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1};");
```

This will be fixed in the upcoming version.

**Comment by geetanjaligandhi** [comment]
Thanks Lanzaa for reply.

I tried above command as suggested by you but is still displays the same error...
While debugging, i found it is failing in recv_execute_cql3_query() method while calling readMessageBegin() method... It returns $mtype =3 then enter in the below if block
  if ($mtype == TMessageType::EXCEPTION) {
    my $x = new TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
and return TApplicationException=HASH(0x8df5cc0) exception...
While debugging it also shows "# Looks like your test exited with 255 just after 1." in error message

Also i am not able to run the testcases which use exec() method in perlcassa.pm.All the testcases mentioned in these files: 
30CQL_create_keyspace.t, 31CQL_basic_queries.t,33CQL_decode_types.t,
38CQL_drop_keyspace.t,40CQL_internal.t have failed for me... 

Please provide the solution...
Thanks,

**Comment by Lanzaa** [comment]
Ok, before investigating further could I get some more information from you?
1. What version of Cassandara are you running?
2. What version of perlcassa?
3. Is it possible for me to see the output of a Data::Dumper of the error? You would have to add something like the following.

``` perl
eval {
 # Stuff that breaks...
}; if ($@) {
 print "Full error message: ".Dumper($@);
}
```

**Comment by geetanjaligandhi** [comment]
1. Apache Cassandra version - 1.1.6
2. perlcassa version - 0.5

Using the above code it shows the same error message as posted earlier.

Thanks,

**Comment by Lanzaa** [comment]
@geetanjaligandhi Ah, Cassandra 1.1.6, I have been testing with 1.2.0 and 1.2.3. I suspect is it a problem with the changes they made between 1.1 and 1.2. Any chance you want to switch to 1.2? If not I will try to find some time to test with 1.1.6/1.1.10.

**Comment by geetanjaligandhi** [comment]
Can you please share any documentation on the usage of perlcassa and all the version compatibility

I tried to use perlcassa with cassandra 1.2.0 

While using describe_all_columnfamilies method i am facing strange issue:
If I create a Column family using cassa API, then describe method list the columnfamily, But If i create a column family using CQL then this method won't list the columnfamily.

Please provide the solution for this problem and If possible share your findings regarding testing of perlcassa with cassandra 1.1.6 

It would be a great help :)

Thanks,

**Comment by mkjellman** [comment]
@geetanjaligandhi it sounds like you have an old version of Cassandra/Types.pm etc on your box somewhere else. Please try on a clean install somewhere to rule out your own box. I don't think this is a problem related to the perlcassa perl module.

**Comment by Lanzaa** [comment]
@geetanjaligandhi I believe the issue with describe_all_columnfamilies and CQL created column families is a known issue with Cassandra itself. Column families created with CQL3 are not visible to the thrift api. Discussion of that is in [CASSANDRA-4924](https://issues.apache.org/jira/browse/CASSANDRA-4924).

It appears that the CQL3 calls are not compatible with cassandra 1.1 or earlier.  It would take a nontrivial amount of effort to make perlcassa compatible with both 1.1 and 1.2. As such I am closing this issue as wontfix. Feel free to comment or reopen this issue if you wish to continue the discussion.

**Comment by geetanjaligandhi** [comment]
I did not understand " it sounds like you have an old version of Cassandra/Types.pm etc on your box somewhere else. " comments suggested by mkjellman. Please elaborate

Please confirm me that with perlacassa can we use regex for querying cassandra and if yes then plz share an example. plz share any documentation or help doc illustrating perlacassa usage.

And In Last Thanks Lanzaa for sharing all the inputs ....
