### ISSUE TITLE
Unusable Counter Columns

### ISSUE THREAD

**Issue by Lanzaa** [mkjellman/perlcassa#4]
There seems to be no way to access counter column data or to unpack more than one type of columnfamily data.

Calls to _unpack_value are always given the column rather than counter_column data. The calls are also not passed the column family option.

**Comment by Lanzaa** [comment]
There is another use of _unpack_value in _deserialize_column_array that I have not changed, but may need to be.

**Comment by mkjellman** [comment]
i manually merged this in 1da9b64. thank you.
