### ISSUE TITLE
Compatability of  perlcassa with Datastax cassandra 3.0

### ISSUE THREAD

**Issue by geetanjaligandhi** [mkjellman/perlcassa#40]
Is perlcassa compatible with datastax cassandra 3.0 ?. 

while trying to use below query with perlcassa
my $res = $obj->exec("SELECT \* FROM $test_keyspace.$cfname1");
throws following error:

Full error message: $VAR1 = bless( {
                 'code' => 1,
                 'message' => 'Invalid method name: \'execute_cql3_query\''
               }, 'TApplicationException' );

Please provide the solution for this

Thanks,
Geetanjali

**Comment by Lanzaa** [comment]
I am not sure which version of Cassandra DataStax is based on. The Perlcassa CQL calls require Cassandra 1.2+. Do you happen to know which version of Cassandra is included by DataStax?

**Comment by iamaleksey** [comment]
DSE 3.0 includes Cassandra 1.1 with some modifications, so not 1.2, and perlcassa wouldn't work with it. DSE with Cassandra 1.2 is in the works, though.

**Comment by Lanzaa** [comment]
Just a quick heads up that the non-CQL calls should work with 1.1. However they are currently being tested only on 1.2.
