### ISSUE TITLE
Create column family with perlcassa

### ISSUE THREAD

**Issue by geetanjaligandhi** [mkjellman/perlcassa#41]
I wanted to create a table as shown below:
CREATE TABLE test_all(key text PRIMARY KEY,   country text,   state text,   city text,   store_name text,  in_stock boolean, store_city text,   store_state float,year int)

How shall i pass the column names and their types to the below method

$obj->column_family(
'action'                  =>'create', # or 'update' or 'drop'
'columnname'         => 'cfname',
'keyspace'       => 'myKeyspace', #optional and not needed it specified in object creation
'comparator_type'    => 'CompositeType(UTF8Type, UTF8Type)',
'key_validation_class     => 'UTF8Type',
'default_validation_class => 'UTF8Type'
);

Please share the exact syntax to create the table as mentioned above.

Thanks,
Geetanjali

**Comment by mkjellman** [comment]
is this for C\* 1.1.x?

**Comment by geetanjaligandhi** [comment]
I am trying this on 1.1.9.3. Just wanted to know how to mention column names in column_family method.

**Comment by mkjellman** [comment]
i'm confused by your question. in the hash just change the element 'columnname' => 'cfname'. It should be as simple as replacing this with the name of the column family you would like to create via the thrift methods.
