### ISSUE TITLE
CQL3 support

### ISSUE THREAD

**Issue by geetanjaligandhi** [mkjellman/perlcassa#42]
Please brief what all functionality can be used with cql3 calls
in terms of 
data type support,
types of query ,
functions 
etc . which can and cannot be invoked using cql3

Thanks
Geetanjali

**Comment by mkjellman** [comment]
http://www.datastax.com/docs/1.2/cql_cli/index ?

I am also working on binary/native support for 1.2. Going forward the perlcassa project will only support C\* 1.2.0+ and CQL3

you can do everything you can do with thrift with cql3

**Comment by geetanjaligandhi** [comment]
What do you mean by CQL3..... does that mean for any specific data types or queries which it should support

**Comment by mkjellman** [comment]
The project today supports CQL3 via Thrift and there is binary (and undocumented) support for the native protocol. We are only supporting 1.2.0+ and i'm not sure how 1.1 will deal with prepared statements compared to 1.2. I know there were some changes even between 3.0.0 and 3.0.1 of the CQL3 spec regarding prepared statements.

i'm not sure i understand the second part of your question. The CQL3 spec is something the client implements but there is plenty of documentation on CQL3 and what it supports in the Apache Cassandra documentation. You should read up there if you have more questions.
