### ISSUE TITLE
Unable to find column family created with cqlsh

### ISSUE THREAD

**Issue by hunsakerbn** [mkjellman/perlcassa#46]
I'm using Cassandra 1.2.5. Using masters from github for perlcassa and thrift-xs
When I try to access a column family(now called table) that I created via cqlsh I get the mesasge: Unable to find the column family users in ks1 at /usr/local/share/perl/5.14.2/perlcassa.pm line 510.

However if I create the column family via cassandra-cli, then perlcassa works without problems.

**Comment by mkjellman** [comment]
CQL3 created Tables aren't accessible via the Thrift methods in perlcassa. You should use the CQL statements if you want to use a CQL3 created table
