### ISSUE TITLE
Timestamps should be microseconds

### ISSUE THREAD

**Issue by Lanzaa** [mkjellman/perlcassa#6]
According to the [Cassandra DataModel](http://wiki.apache.org/cassandra/DataModel/) the convention for timestamps is to use microseconds.

Because perlcassa uses seconds, a deletion or insertion from the cassandra cli or cqlsh cannot be overwritten by perlcassa. Switching to microseconds will make perlcassa compatible with the cli and cqlsh, which both use microseconds.

**Comment by mkjellman** [comment]
this has been merged into master. thank you.
