### ISSUE TITLE
Unable to manipulate keyspaces

### ISSUE THREAD

**Issue by Lanzaa** [mkjellman/perlcassa#9]
The perlcassa library currently lacks the ability to manipulate keyspaces.

I propose two new methods, create_keyspace and drop_keyspace.

``` perl
create_keyspace(
  name => 'ks_name',
  # Optional
  replication_strategy => 'SimpleStrategy',
  durable_writes => 1,
  strategy_options => undef,
);
```

``` perl
drop_keyspace(
  name => 'ks_name'
);
```

**Comment by mkjellman** [comment]
i'm wondering if we should provide this though instead of forcing the use of CQL3...

**Comment by Lanzaa** [comment]
The CQL3 stuff now allows manipulation of keyspaces. I'm closing this issue.
